version: '2'

services:
  frontend:
    build: ./frontend
    command: npm run dev
    volumes:
      - ./frontend/src:/project/src
    ports:
      - "8080:8080"
  db:
    image: postgres
  backend:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/project
    ports:
      - "8000:8000"
    depends_on:
      - db
